# Generated by Django 3.0.4 on 2020-06-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustionanalysistest',
            name='excess_air',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
