# Generated by Django 3.0.4 on 2020-06-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
        ('combustion', '0002_auto_20200616_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='combustionanalysistest',
            name='analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Analisis', to='analisis.Analisis'),
        ),
    ]
