# Generated by Django 3.0.4 on 2020-04-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=100)),
                ('min_pressure', models.DecimalField(decimal_places=2, max_digits=2)),
                ('fuel_type', models.CharField(choices=[('GAS', 'Natural Gas'), ('N2 OIL', 'Number 2 Oil')], default='GAS', max_length=10)),
            ],
        ),
    ]
