# Generated by Django 3.0.4 on 2020-04-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burner',
            name='min_pressure',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
